[package]
name = "multi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
tiny-tokio-actor = "0.3"
env_logger = "0.11.2"
log = "0.4.20"

