base_url = "https://rune-rs.github.io"

title = "The Rune Programming Language"
description="Party dynamically like it's 1995"
default_language = "en"

generate_feed = true
feed_filename = "rss.xml"
rss_limit = 20
compile_sass = true
highlight_code = true
build_search_index = false
extra_syntaxes = ["syntaxes"]

taxonomies = [
  { name = "categories", feed = true, render = false },
  { name = "tags", feed = true, render = false },
]

[markdown]
highlight_theme = "kronuz"
highlight_code = true

[extra]
profile = "logo.png"
github = "rune-rs"
discord = "https://discord.gg/v5AeNkT"
book = "rune-rs.github.io/book/"
playground = """
fn fib(n) {
    if n <= 1 {
        n
    } else {
        fib(n - 1) + fib(n - 2)
    }
}

pub fn main() {
    fib(15)
}
"""
